[package]
name = "ocs_cam_core"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
cadkernel = { git = "https://github.com/HakanSeven12/cadkernel.git", rev = "0507b720fef47bd7da0d4f777f97f1743a4f4038", features = ["offset"] }
serde = { version = "1", features = ["derive"] }

